openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /products/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        examples:
          GET_DETAILS:
            value: 100
    get:
      responses:
        200:
          description: Product details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product_details'
              examples:
                GET_DETAILS:
                  value:
                    - id: 10
                      name: La Bouledogue
                      quantity: 5
                    - id: 20
                      name: Duvel
                      quantity: 50
  /products:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/product_details'
            examples:
              CREATE_PRODUCTS:
                value:
                  - id: 10
                    name: La Bouledogue
                    quantity: 5
                  - id: 20
                    name: Duvel
                    quantity: 50
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product_details'
              examples:
                CREATE_PRODUCTS:
                  value:
                    - id: 10
                      name: La Bouledogue
                      quantity: 11
                    - id: 20
                      name: Duvel
                      quantity: 51

components:
  schemas:
    product_details:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer