openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /products/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        examples:
          GET_DETAILS:
            value: 10
          NOT_FOUND:
            value: 999
    get:
      responses:
        200:
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product_details'
              examples:
                GET_DETAILS:
                  value:
                    id: 10
                    name: La Bouledogue
                    quantity: 5
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                NOT_FOUND:
                  value:
                    error: 'NOT FOUND'
  /products:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product_details'
            examples:
              CREATE_PRODUCT:
                value:
                  id: 10
                  name: 'Duvel'
                  quantity: 24
              ASYNC:
                value:
                  id: 100
                  name: 'Goudale'
                  quantity: 24
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product_details'
              examples:
                CREATE_PRODUCT:
                  value:
                    id: 10
                    name: 'Duvel'
                    quantity: 24
        202:
          description: ACCEPTED
          headers:
            location:
              schema:
                type: string
              examples:
                ASYNC:
                  value: "https://server.com"


components:
  schemas:
    product_details:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer